### PR TITLE
fix(android): use AndroidX `OnBackPressedCallback` instead of `OnBackInvokedCallback`

### PR DESCRIPTION
**Pull request by GitToTheHub**
### Platforms affected
Android

### Motivation and Context

- `CoreAndroid.java` referenced `OnBackInvokedCallback` directly (including lambda generation), which can trigger class resolution on runtimes that do not contain that API.
- Replaced `OnBackInvokedCallback` with AndroidX `OnBackPressedCallback`
- Fixes error message: `java.lang.Class<org.apache.cordova.CoreAndroid$$ExternalSyntheticLambda0>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;` on older Android versions pre API Level 33 (Android 13)
- The use of `OnBackInvokedCallback` and `OnBackInvokedDispatcher` was introduced with PR https://github.com/apache/cordova-android/pull/1831
- Generated-By: GPT-5.3-Codex, GitHub Copilot Chat

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]
Assuming that test passes I believe we are good!

**Comment by MoekoNakajima** [comment]
Could I ask you a question?
Is there a scheduled release date for this update?
If so, I would appreciate it if you could let me know.

**Comment by GitToTheHub** [comment]
Hi currently there is no scheduled release date. I think currently we have not a good point to make release, since there are some things around the statusbar and edge-to-edge

**Comment by MoekoNakajima** [comment]
Thank you for letting me know. I understand the situation. I am looking forward to the release!

**Comment by MoekoNakajima** [comment]
I tried applying this fix, but the Back button didn't work.
Are you considering any additional fixes?

**Comment by GitToTheHub** [comment]
Can you describe more what you did? Did you tried the latest master of cordova-android? Which Android version did you test on? Did you tried it on an emulator or a real device? This PR here does not fix all back button problems. The PR #1910 should fix back button issues.

**Comment by MoekoNakajima** [comment]
>Did you tried the latest master of cordova-android?
> The PR https://github.com/apache/cordova-android/pull/1910 should fix back button issues.

I had updated to Cordova Android 15.0.0, but I hadn't tried the latest master branch yet.
I have now tested the latest master branch (which includes PR #1910 ) and confirmed that the back button works properly.
Thank you for pointing that out.

**Comment by GitToTheHub** [comment]
Hi, I'm glad to hear that it works now for you
