### ISSUE TITLE
TypeError: nativeApiProvider.get(...).exec is not a function

### ISSUE THREAD

**Issue by mzealey** [apache/cordova-android#726]
# Bug Report

I am getting an error on app startup on some production installs, but cannot reproduce locally.

This is new to cordova 9 / cordova-android 8.0.0 as it was working on cordova 8, cordova-android 7.1.4 version. Due to the nature of the error I would guess it is the cordova-android side that is causing it but I may be wrong.

### What does actually happen?

Here is error and stack trace that my auto reporting system picks up:

```
TypeError: nativeApiProvider.get(...).exec is not a function
    - androidExec()@file:///android_asset/www/cordova.js:960:40
    - Channel.<anonymous>()@file:///android_asset/www/cordova.js:1470:13
    - Channel.fire()@file:///android_asset/www/cordova.js:840:23
    - {anonymous}()@file:///android_asset/www/cordova.js:1296:28
    - Channel.f()@file:///android_asset/www/cordova.js:687:25
    - Channel.fire()@file:///android_asset/www/cordova.js:840:23
    - {anonymous}()@file:///android_asset/www/cordova.js:1283:32
    - onScriptLoadingComplete()@file:///android_asset/www/cordova.js:1665:5
    - scriptLoadedCallback()@file:///android_asset/www/cordova.js:1682:13
    - HTMLScriptElement.<anonymous>()@file:///android_asset/www/cordova.js:1636:17
```

## Information

So far I have seen this happening on the following user agents on live devices:

```
 Mozilla/5.0 (Linux; Android 6.0.1; Venus_V3_5040_2GB Build/VASP54; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36
 Mozilla/5.0 (Linux; Android 6.0; ZTE BLADE L7 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36
 Mozilla/5.0 (Linux; Android 7.0; SM-N920C Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36
 Mozilla/5.0 (Linux; Android 7.1.1; SM-J510FN Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.137 Mobile Safari/537.36
 Mozilla/5.0 (Linux; Android 7.1.1; SM-J510FQ Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36
```

### Version information

Android studio 2.3.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Closing as stale.
